services:
  app:
    container_name: 'java-spring-crm-uralintern'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/internships
      - SPRING_DATASOURCE_USERNAME=crm_admin
      - SPRING_DATASOURCE_PASSWORD=bitrix24
      - SECURITY_JWT_SECRET=kkpCT7HHsKjkXCfVKzz7JA9Dgwhkg0xXqequdWhH60onkqPnU83hZ831b3eOYvyQdMytDFNfjMwZUBC3DHYaRg==
      - SECURITY_JWT_EXPIRATION=86400000
      - SECURITY_JWT_REFRESH_EXPIRATION=604800000
      - SPRINGDOC_SWAGGER_UI_URL=/swagger.json
    command: ["sh", "-c", "while ! nc -z db-postgres 5432; do sleep 1; done; java -jar build/libs/CRM-Module-1.0-SNAPSHOT.jar"]
    ports:
      - "8080:8080"
    restart: always
    networks:
      - main-network

  db-postgres:
    image: postgres:latest
    container_name: "database_postgres"
    environment:
      POSTGRES_DB: internships
      POSTGRES_USER: crm_admin
      POSTGRES_PASSWORD: bitrix24
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/init-script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - main-network

volumes:
  db_data:
    driver: local

networks:
  main-network:
    driver: bridge